# TODOpipeline {
    agent any
    environment {
      REPOSITORY="widgetario"
      RELEASE="21.12"
    }
    stages {
        stage('Audit tools') {                        
            steps {
                sh '''
                  docker version
                  docker compose version
                '''
            }
        }
        stage('Build') {
            steps {
              echo "Building images for release: ${RELEASE}"
                sh '''
                  docker-compose -f project/compose/docker-compose.yml -f project/compose/build.yml build --pull
                '''
              }
            }
        }
        stage('Smoke Test') {
          steps {
              echo "Running local containers"
              sh '''
                docker-compose -p smoke -f project/compose/docker-compose.yml -f project/compose/test.yml up -d

                products_address=$(docker port smoke_products-api_1 80)
                stock_address=$(docker port smoke_stock-api_1 8080)
                web_address=$(docker port smoke_web_1 80)

                curl --fail "${stock_address/0.0.0.0/localhost}/healthz"
                curl --fail "${web_address/0.0.0.0/localhost}/up"
                curl --fail "${products_address/0.0.0.0/localhost}/healthz"
              '''
            }
        }
    }
    post{
        always {
             sh '''
                docker-compose -p smoke -f project/compose/docker-compose.yml -f project/compose/test.yml down
            '''
        }
    }
}